const { defineConfig, devices } = require('@playwright/test');
require('dotenv').config({ path: '.env' });

const BASE_URL = process.env.BASE_URL || 'https://admin-dev.mediplanner.mx/';

module.exports = defineConfig({
  testDir: './tests',
  timeout: 60000,
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: [
    ['html', { open: 'never' }],
    ['list']
  ],
  use: {
    baseURL: BASE_URL,
    trace: 'on-first-retry',
    screenshot: 'on',
    video: 'off',
    headless: false,
    viewport: null,
    actionTimeout: 15000,
    navigationTimeout: 30000,
    launchOptions: { slowMo: 50, args: ['--start-maximized'], ...(process.env.PW_CHROMIUM_PATH ? { executablePath: process.env.PW_CHROMIUM_PATH } : {}) },
  },
  projects: [
    {
      name: 'setup',
      testMatch: /.*\.setup\.ts/,
      use: { ...devices['Desktop Chrome'], video: 'off', screenshot: 'off' },
      timeout: 30000,
    },
    {
      name: 'dashboard-explorar',
      testMatch: /dashboard\.explorar\.spec\.js/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 120000,
    },
    {
      name: 'dashboard',
      testMatch: /dashboard\.spec\.js/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 90000,
    },
    {
      name: 'reportes',
      testMatch: /reportes\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 120000,
    },
    {
      name: 'ajustes-servicios',
      testMatch: /ajustes\.servicios\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 90000,
    },
    {
      name: 'ajustes-explorar',
      testMatch: /ajustes\.explorar\.spec\.js/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 180000,
    },
    {
      name: 'reportes-explorar',
      testMatch: /reportes\.explorar\.spec\.js/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 120000,
    },
    {
      name: 'percentil-explorar',
      testMatch: /percentil\.explorar\.spec\.js/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 180000,
    },
    {
      name: 'recetas-explorar',
      testMatch: /recetas\.explorar\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 180000,
    },
    {
      name: 'recetas',
      testMatch: /recetas\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 180000,
    },
    {
      name: 'vacunacion-explorar',
      testMatch: /vacunacion\.explorar\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 240000,
    },
    {
      name: 'vacunacion-ciclo-completo',
      testMatch: /vacunacion\.ciclo-completo\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 600000,
    },
    {
      name: 'appointments-create',
      testMatch: /appointments\.create\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 90000,
    },
    {
      name: 'doctor-consultation',
      testMatch: /consultation\.full-flow\.spec\.(js|ts)/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 300000,
    },
    {
      name: 'consultation-inputs-validation',
      testMatch: /consultation\.inputs-validation\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 300000,
    },
    {
      name: 'system-health',
      testMatch: /system-health\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 30000,
    },
    {
      name: 'ingresos',
      testMatch: /ingresos\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 300000,
    },
    {
      name: 'subir-estudios',
      testMatch: /subir-estudios\.spec\.ts/,
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      timeout: 120000,
    },
    {
      name: 'stress-citas',
      testMatch: '**/citas.stress.test.ts',
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 300000,
    },
    {
      name: 'stress-pacientes',
      testMatch: '**/pacientes.stress.test.ts',
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 300000,
    },
    {
      name: 'stress-ingresos',
      testMatch: '**/ingresos.stress.test.ts',
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 300000,
    },
    {
      name: 'stress-login',
      testMatch: '**/login.stress.test.ts',
      timeout: 300000,
    },
    {
      name: 'stress-informacion-paciente',
      testMatch: '**/informacion-paciente.stress.test.ts',
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 300000,
    },
    {
      name: 'stress-facturacion',
      testMatch: '**/facturacion.stress.test.ts',
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 600000,
    },
    {
      name: 'stress-antecedentes',
      testMatch: '**/antecedentes.stress.test.ts',
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 600000,
    },
    {
      name: 'stress-diagnosticos',
      testMatch: '**/diagnosticos.stress.test.ts',
      use: { ...devices['Desktop Chrome'], storageState: 'storageState.json', viewport: null, deviceScaleFactor: undefined },
      dependencies: ['setup'],
      timeout: 600000,
    },
  ],
});
