from fpdf import FPDF
import os

class ReportePDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Reporte de Test - Mediplaner', 0, 1, 'C')
        self.ln(5)

# Test 1: test_perfil_datos_personales
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_perfil_datos_personales', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 36 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de validacion de datos personales del usuario. Verifica las validaciones de campos obligatorios y formatos correctos.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar a Perfil -> Datos Personales\n2. Limpiar campos Nombre y Apellido\n3. Verificar boton deshabilitado sin datos\n4. Ingresar datos validos\n5. Pruebas de CURP, correo y telefono\n6. Click en Guardar y Continuar')
pdf.ln(10)
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_perfil_datos_personales.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 2: test_perfil_cuenta
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_perfil_cuenta', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 54 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de gestion de suscripcion y cuenta.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar a Perfil -> Cuenta\n2. Ver todos los planes (4 encontrados)\n3. Cambiar ciclo de facturacion\n4. Cancelar suscripcion -> Mantener')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_perfil_cuenta.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 3: test_perfil_compartir
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_perfil_compartir', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 47 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de comparticion de documentos con contactos.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar a Perfil -> Compartir\n2. Verificar Compartido Parcialmente\n3. Agregar nuevo contacto\n4. Validaciones de telefono\n5. Invitar y Compartir')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_perfil_compartir.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 4: test_perfil_progreso
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_perfil_progreso', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 59 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de seguimiento de progreso e insignias.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar a Perfil -> Progreso\n2. Click en Retos -> Insignias\n3. Click en badge Cliente #1\n4. Regresar -> Medicamentos\n5. Regresar a Inicio')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_perfil_progreso.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 5: test_perfil_historial_medico
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_perfil_historial_medico', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 94 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test completo de historial medico.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar Perfil -> Historial Medico\n2. Antecedentes patologicos (Asma -> Enviar)\n3. Heredofamiliares (Miopia -> Enviar)\n4. Alergias (Agregar aleatorio -> Enviar)\n5. Gineco-Obstetricos (Planificacion/Embarazos/Citologias -> No -> Enviar)')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_perfil_historial_medico.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 6: test_perfil_documentos
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_perfil_documentos', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 45 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de carga de documentos con archivo.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar Perfil -> Documentos\n2. Agregar documento\n3. Ingresar nombre (aleatorio)\n4. Ingresar comentario (aleatorio)\n5. Seleccionar archivo\n6. Guardar')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_perfil_documentos.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 7: test_consultas_previas
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_consultas_previas', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 91 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de consultas previas y carga de estudios.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Consultas -> Previas\n2. Seleccionar consulta Terminada\n3. Navegar pestañas (Receta/Exploracion/Estudios)\n4. Cargar resultados desde Galeria\n5. Finalizar')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_consultas_previas.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 8: test_medicos_especialidad
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_medicos_especialidad', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 61 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de filtros en medicos por especialidad.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar a Medicos\n2. Resetear filtros\n3. Buscar especialidad Internista\n4. Aplicar filtro\n5. Seleccionar doctor\n6. Ver detalles')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_medicos_especialidad.pdf"
pdf.output(output)
print(f"Generado: {output}")

# Test 9: test_medicos_estado
pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_medicos_estado', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: 61 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 20/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de filtros en medicos por estado.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Navegar a Medicos\n2. Resetear filtros\n3. Seleccionar filtro estado Queretaro\n4. Aplicar filtro\n5. Seleccionar doctor\n6. Ver detalles')
output = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs\test_medicos_estado.pdf"
pdf.output(output)
print(f"Generado: {output}")

print("\n=== 9 PDFReports generados exitosamente ===")