from fpdf import FPDF
import os

class ReportePDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Reporte de Test - Mediplaner', 0, 1, 'C')
        self.ln(5)

output_dir = r"C:\Users\pandr\OneDrive\00_Pedro_Quijada\03_RYM-Solutions\Mediplaner\VS Code testing\MediplannerAppiumAutomation\Appium\reports\Reportes PDFs"

pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_dependientes_agregar', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: ~110 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 22/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de creacion de nuevo dependiente. Verifica el flujo completo de agregar un dependiente desde el menu de perfil.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Perfil -> Agregar dependiente\n2. Llenar: Nombre, Apellidos, Fecha, Sexo, Parentesco\n3. Continuar -> Dependiente creado')
pdf.output(os.path.join(output_dir, "test_dependientes_agregar.pdf"))
print("Generado: test_dependientes_agregar.pdf")

pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_dependientes_desvincular', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: ~55-101 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 22/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de desvinculacion de cotitular y cierre de sesion con re-login.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Perfil -> Dependiente -> Compartir\n2. Desvincular cotitular\n3. Cerrar sesion\n4. Re-login con nuevas credenciales')
pdf.output(os.path.join(output_dir, "test_dependientes_desvincular.pdf"))
print("Generado: test_dependientes_desvincular.pdf")

pdf = ReportePDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 14)
pdf.cell(0, 10, 'Test: test_dependientes_agregar_dos', 0, 1, 'L')
pdf.set_font('Arial', '', 11)
pdf.cell(0, 8, 'Resultado: PASSED', 0, 1, 'L')
pdf.cell(0, 8, 'Tiempo: ~110 segundos', 0, 1, 'L')
pdf.cell(0, 8, 'Fecha: 22/04/2026', 0, 1, 'L')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Descripcion:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, 'Test de creacion de dos dependientes desde el perfil de un dependiente.')
pdf.ln(3)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Flujo Ejecutado:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.multi_cell(0, 5, '1. Crear Dependiente 1\n2. Seleccionar perfil\n3. Crear Dependiente 2\n4. Continuar -> Dos dependientes creados')
pdf.output(os.path.join(output_dir, "test_dependientes_agregar_dos.pdf"))
print("Generado: test_dependientes_agregar_dos.pdf")

print("\n=== 3 PDF Reports de Dependientes generados exitosamente ===")